version: 0.0
os: linux
files:
  - source: /target
    destination: /var/www/java-app/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/cleanup
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root