version: 0.2
  
phases:
  install:
    runtime-versions:
        java: corretto11
    commands:
      - echo Entered the install phase...
       
  build:
    commands:
      - mvn -B -DskipTests clean package
artifacts:
  files:
    - '**/*'