version: 0.2
  
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - mvn install
  build:
    commands:
      - mvn -B -DskipTests clean package
artifacts:
  files:
    - '**/*'