version: 0.2
  
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Nothing to do
  build:
    commands:
      - mvn -B -DskipTests clean package
artifacts:
  files:
    - target/**/*
    - scripts/**/*
    - appspec.yml